-- Monitor configuration — generated by Monitor Settings on 2026-09-06
-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- List monitors and supported resolutions with: hyprctl monitors all

hl.env("GDK_SCALE", "1")

hl.monitor({ output = "DP-1", mode = "2560x1440@144", position = "0x0", scale = 1 })
hl.monitor({ output = "HDMI-A-2", mode = "2560x1440@144", position = "2560x0", scale = 1 })
